name: Service Creation Request
description: Request automated service creation with SuperClaude
title: "[Service] "
labels: ["service-type", "automated"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🚀 SuperClaude Service Creation
        
        Describe your service in natural language. The Architect persona will analyze your requirements and automatically create repositories, issues, and infrastructure.

  - type: textarea
    id: description
    attributes:
      label: Service Description
      description: Describe what you want to build in natural language (be as detailed as you like)
      placeholder: |
        I need a Todo Management Web App with:
        - User authentication (signup, login, logout)
        - Create, read, update, delete todos
        - Mark todos as complete/incomplete
        - Set due dates and priorities
        - Filter and search todos
        - Categories or tags for organization
        - Modern, responsive UI
        - Real-time updates
      value: |
        I need a Todo Management Web App with:
        - User authentication (signup, login, logout)
        - Create, read, update, delete todos
        - Mark todos as complete/incomplete
        - Set due dates and priorities
        - Filter and search todos
        - Categories or tags for organization
        - Modern, responsive UI
        - Real-time updates
    validations:
      required: true